oraclejdk-8:
  build: oraclejdk-8
  container_name: oraclejdk-8
  command: "true"
  restart: "no"

teamcity:
  build: teamcity
  restart: always
  ports:
  - "8111:8111"
  volumes:
  - ./teamcity/storage:/root/BuildServer

teamcityagent-python:
  build: teamcity-agent-python
  restart: always
  links:
  - teamcity